// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfgbwedojxpcnqemdzbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZ2J3ZWRvanhwY25xZW1kemJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjU1MjMsImV4cCI6MjA1NzMwMTUyM30.4unDryHUOYqlcD6zKcVhP02mIODqf3TU7N3vynxrkU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);